version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pf_postgres
    restart: always
    environment:
      POSTGRES_DB: projectflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pf_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pf_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db.krcpxgfxvukickehjtnw.supabase.co:5432/postgres?sslmode=require
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: "P1,o2,i3,u4"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: 407780T00Y587123984712034981723491823491823498172349817239487123
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pf_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
